config/routes.rb
GalleryOnRails::Application.routes.draw do

  resources :permissions

  resources :albums do
    resources :pictures
  end

  get "admin" => "admin#index", :as => "admin"

  get "sessions/new"
  get "users/new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'albums#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :name, :value
  has_many :permission_assignments
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @permissions }
    end
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
    @permission = Permission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @permission }
    end
  end

  # GET /permissions/new
  # GET /permissions/new.json
  def new
    @permission = Permission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @permission }
    end
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(params[:permission])

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render json: @permission, status: :created, location: @permission }
      else
        format.html { render action: "new" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.json
  def update
    @permission = Permission.find(params[:id])

    respond_to do |format|
      if @permission.update_attributes(params[:permission])
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to permissions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.haml
= simple_form_for(@permission) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :value

  .form-actions
    = f.button :submit

app/views/permissions/edit.html.haml
%h1 Editing permission

= render 'form'

= link_to 'Show', @permission
\|
= link_to 'Back', permissions_path

app/views/permissions/index.html.haml
%h1 Listing permissions

%table
  %tr
    %th Name
    %th Value
    %th
    %th
    %th

  - @permissions.each do |permission|
    %tr
      %td= permission.name
      %td= permission.value
      %td= link_to 'Show', permission
      %td= link_to 'Edit', edit_permission_path(permission)
      %td= link_to 'Destroy', permission, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Permission', new_permission_path

app/views/permissions/new.html.haml
%h1 New permission

= render 'form'

= link_to 'Back', permissions_path

app/views/permissions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @permission.name
%p
  %b Value:
  = @permission.value

= link_to 'Edit', edit_permission_path(@permission)
\|
= link_to 'Back', permissions_path