config/routes.rb
GalleryOnRails::Application.routes.draw do

  resources :permissions

  resources :albums do
    resources :pictures
  end

  get "admin" => "admin#index", :as => "admin"

  get "sessions/new"
  get "users/new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name, :albumthumbnail, :promoted
  has_many :pictures
  mount_uploader :albumthumbnail, ImageUploader
  scope :promoted, where(promoted: true).first

  after_create :add_permissions

  def add_permissions
  	Permission.create(name: "Edit " + self.name, value: "edit_" + self.name)
  	Permission.create(name: "View " + self.name, value: "view_" + self.name)
  	Permission.create(name: "Change Users " + self.name, value: "chg_user_" + self.name)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter :require_login, :only => [:new, :edit, :destroy, :create, :update]
  before_filter :get_promoted_pics, :only => :index

  def get_promoted_pics
    if Album.promoted.any?
      @promoted_pics = Album.promoted.first.pictures
    else
      @promoted_pics = {}
    end
  end

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.includes(:pictures).all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.includes(:pictures).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.includes(:pictures).find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to admin_path, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to edit_album_path(@album), notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Album wurde geloescht.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
.row
  .large-4.columns
    = image_tag @album.albumthumbnail_url(:thumbsmal).to_s

  .large-8.columns
    = form_for @album do |f|
      - if @album.errors.any?
        #error_explanation
          %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
          %ul
            - @album.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :name
        = f.text_area :name
      .field
        = f.label :description
        = f.text_area :description
      .field
        = f.label :albumthumbnail
        = f.file_field :albumthumbnail
      .field
        = f.label :promoted
        = f.check_box :promoted
      .actions
        = f.submit 'Save', class: "button"

app/views/albums/edit.html.haml
- key = Rails.application.config.session_options[:key]
.row
  .large-12.columns.large-centered
    .large-2.columns.panel

      = render "shared/side_nav"

    .large-10.columns
      %h2
        Admin Dashboard - Editing album
      .row#pictures
        = render @album.pictures

      =link_to "Bild Hinzufügen", new_album_picture_path(@album), class: "button", "data-reveal-id" => "add-pictures"
      
      = render 'form'

-content_for :modals do
  .reveal-modal.medium#add-pictures
    = form_for [@album, Picture.new] do |f|
      = f.label :image, "Upload Pictures:"
      = f.file_field :image, multiple: true, name: "picture[image]"

    #progress-bars
    -# = render "shared/progress_bar"
    %a.close-reveal-modal
      &#215;

app/views/albums/index.html.haml
.row
  .large-12.columns

    / Desktop Slider
    #slider
      = image_tag @promoted_pics.first.image_url.to_s if @promoted_pics.any?
    / End Desktop Slider

    / Mobile Header
    .row
      .small-12.show-for-small
        %br/
        -if @promoted_pics.any?
          %img{:src => @promoted_pics.first.image_url(:thumbbig).to_s}/
    / End Mobile Header

%br/
.row
  .large-12.columns
    .row

      / Thumbnails
      - @albums.each do |album|
        .large-3.small-6.columns
          %a{:href => album_pictures_path(album)}
            %img{:src => album.albumthumbnail_url(:thumbsmal).to_s}/
          %h6.panel
            = album.name
      / End Thumbnails

/ For enabled javascript add slider
- slider = escape_javascript(render 'shared/slider')
- content_for :scripts do
  :javascript
    $("#slider").replaceWith("#{slider}");
    $(document).foundation();

app/views/albums/new.html.haml
.row
  .large-12.columns.large-centered
    .small-2.columns.panel

      = render "shared/side_nav"

    .small-10.columns
      %h2
        Admin Dashboard - New Album

      = render 'form'

app/views/albums/show.html.haml
.row
  .large-12.columns
  %h2
    = @album.name
  %p
    = @album.description
.row
  .large-12.columns
    = render @album.pictures