config/routes.rb
GalleryOnRails::Application.routes.draw do

  resources :permissions

  resources :albums do
    resources :pictures
  end

  get "admin" => "admin#index", :as => "admin"

  get "sessions/new"
  get "users/new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'albums#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :description, :path, :image
  belongs_to :album
  mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_filter :require_login, :only => [:new, :edit, :destroy, :create, :update]
  before_filter :get_album

  def get_album
    @album = Album.find(params[:album_id])
  end

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @album.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.html # edit.html.haml
      format.js # edit.js
    end
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @album.pictures.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to edit_album_path(@album), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to edit_album_path(@album), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @album = @picture.album
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to edit_album_path(@album), notice: 'Bild wurde geloescht.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.haml
= form_for [@album, @picture], :html => {:multipart => true} do |f|
  - if @picture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
      %ul
        - @picture.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save', class: "button"

app/views/pictures/_picture.html.haml
.large-6.small-6.columns
  %img{:src => picture.image_url(:thumbbig).to_s}
  .panel
    =link_to "Edit", edit_album_picture_path(@album, picture), remote: true
    =link_to "Destroy", [@album, picture], :method => :delete, :data => { :confirm => 'Are you sure?' }
    %h6
      = picture.description

app/views/pictures/_picture_modal.html.haml
.reveal-modal.medium{id: "picture" + @picture.id.to_s}
  .row
    .large-12.columns
      = image_tag @picture.image_url.to_s
  = render "form"
  %a.button{href:"#", "data-reveal-id" => "picture" + @picture.id.to_s, id: "button" + @picture.id.to_s, style: "display: none;"} 
    x
  %a.close-reveal-modal
    &#215;

app/views/pictures/edit.html.haml
.row
  .large-12.columns.large-centered
    .large-2.columns.panel

      = render "shared/side_nav"

    .large-10.columns
      %h2
        Admin Dashboard - Editing picture
      .row
        .large-12.columns
          = image_tag @picture.image_url.to_s
      = render "form"


-content_for :modals do
  = render 'picture_modal'

app/views/pictures/index.html.haml
.row
  .large-12.columns.large-centered
    %h2
      = @album.name
    %p
      = @album.description
  .row
    .large-12.columns.large-centered
      %ul.clearing-thumbs{"data-clearing" => ""}
        -@album.pictures.each do |pic|
          %li{style: "list-style-type:none; float:left; margin:5px"}
            %a.th{href: pic.image_url.to_s}
              %img{src: pic.image_url(:thumbsmal).to_s, "data-caption" => pic.description}

app/views/pictures/new.html.haml
.row
  .large-12.columns.large-centered
    .small-2.columns.panel

      = render "shared/side_nav"

    .small-10.columns
      %h2
        Admin Dashboard - Picture New

      = render 'form'

app/views/pictures/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @picture.description
%p
  = image_tag @picture.image_url.to_s