config/routes.rb
GalleryOnRails::Application.routes.draw do

  resources :permissions

  resources :albums do
    resources :pictures
  end

  get "admin" => "admin#index", :as => "admin"

  get "sessions/new"
  get "users/new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'albums#index'

end

app/views/layouts/_footer.html.haml
/ Footer
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p &copy; Copyright David Elvers 2013
      .large-6.columns
        %ul.inline-list.right
          -if logged_in?
            %li
              =link_to "Admin", admin_path
          %li
            %a{:href => "#"} Impressum
          %li
            %a{:href => "#"} About

/ End Footer

app/views/layouts/_navigation.html.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{:href => "/"}
          Gallery On Rails

    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span menu
  
  %section.top-bar-section
    / Left Buttons
    %ul.left
      %li
        %a{:href => "#"} Start
      %li
        %a{:href => "#"} Albums
    / Right Buttons
    %ul.right
      -if logged_in?
        %li
          =link_to "Logout", logout_path
      -else
        %li
          =link_to "Login", login_path, remote: true

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GalleryOnRails
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags

  %body
    .row
      .large-12.columns
      
        / Navigation
        = render "layouts/navigation"
        / End Navigation

        / Content
        = yield
        / End Content

        / Footer
        = render "layouts/footer"
        / End Footer

    #modals
    = yield :modals

    = javascript_include_tag "application"
    = yield :scripts